sudo: enabled
services:
    - docker
before_script:
    - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
script:
    - docker build -t rakudo-star ./$VERSION/$VARIANT

env:
    - VERSION='2024.02' VARIANT='bookworm'
    - VERSION='2024.02' VARIANT='alpine3.19'
